echo " NOTE :"
sleep 1
echo " SEBELUM MASUK KE TOOLS NYA ANDA BUAT FILE YANG MAU ENC ATAU DNC "
sleep 1
echo " CARA NYA KETIKAN ( nano coba.sh ) SESUDAH KETIKAN ITU TEMPEL FILE NYA "
sleep 1
echo " SESUAI BUAT FILE NYA LALU KETIKAN LAGI BUAT RUN SC NYA KETIK bash index.sh "